# Simulation Exercises

### How likely is it that you roll doubles when rolling two dice?

In [1]:
import numpy as np
import pandas as pd

In [2]:
n_trials = nrows = 10
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[2, 5],
       [6, 1],
       [1, 6],
       [3, 4],
       [4, 5],
       [5, 5],
       [6, 6],
       [2, 1],
       [5, 1],
       [6, 1]])

In [3]:
def doubles_trial(rolls):
    return np.array([roll[0] == roll[1] for roll in rolls])
doubles_bool = doubles_trial(rolls)
doubles_bool


array([False, False, False, False, False,  True,  True, False, False,
       False])

In [4]:
doubles_rate = doubles_bool.mean()
doubles_rate

0.2

### If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
n_trials = nrows = 10000
n_coins = ncols = 8

flips = np.random.choice([0, 1], (n_trials, n_coins))
flips

array([[1, 0, 1, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1]])

In [6]:
heads_bool = flips == 1
heads_bool
df_heads = pd.DataFrame(heads_bool)
df_heads

0      1      2      3      4      5      6      7
0      True  False   True  False   True  False  False   True
1     False  False  False   True  False   True   True   True
2     False  False  False  False  False  False  False   True
3     False  False  False  False   True   True  False   True
4      True   True   True   True   True   True   True  False
...     ...    ...    ...    ...    ...    ...    ...    ...
9995  False  False   True   True  False   True   True   True
9996  False   True   True   True   True  False  False  False
9997  False  False   True  False   True  False  False  False
9998   True  False   True  False   True  False  False  False
9999   True   True   True   True  False   True   True   True

[10000 rows x 8 columns]

In [7]:
exactly_three = ((df_heads.sum(axis=1)) == 3).mean()
exactly_three

0.2089

In [8]:
more_than_three = ((df_heads.sum(axis=1)) > 3).mean()
more_than_three

0.6461

### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [9]:
n_sims = 100000
n_billboards = 2

drive_by = np.random.choice([1, 0], (n_sims, n_billboards))
drive_by

array([[0, 1],
       [1, 0],
       [0, 0],
       ...,
       [1, 0],
       [0, 0],
       [0, 1]])

In [10]:
ds_df = pd.DataFrame(drive_by)
ds_df

0  1
0      0  1
1      1  0
2      0  0
3      1  1
4      1  1
...   .. ..
99995  0  1
99996  0  0
99997  1  0
99998  0  0
99999  0  1

[100000 rows x 2 columns]

In [11]:
ds_df.sum(axis=1) == 2

0        False
1        False
2        False
3         True
4         True
         ...  
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, P(woman taller than man)?
When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?